apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dicekeeper-dev-uploads
  namespace: student-it200233
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
