DROP DATABASE IF EXISTS keycloak;
DROP USER IF EXISTS keycloak;

CREATE USER keycloak WITH PASSWORD 'dicekeeper' LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION CONNECTION LIMIT -1;
CREATE DATABASE keycloak WITH OWNER=keycloak ENCODING='UTF8' CONNECTION LIMIT=-1;

DROP DATABASE IF EXISTS keeperofthedice;
DROP USER IF EXISTS keeperofthedice;

CREATE USER keeperofthedice WITH PASSWORD 'dicekeeper' LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION CONNECTION LIMIT -1;
CREATE DATABASE keeperofthedice WITH OWNER=keeperofthedice ENCODING='UTF8' CONNECTION LIMIT=-1;
